import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/header/Header";
import ParticlesBackground from "@/component/ParticlesBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <ParticlesBackground />

        <div
          className="absolute inset-0 flex justify-center items-center
  mt-64 md:mt-[25rem] lg:mt-[40rem] xl:mt-[60rem]"
        >
          <img src="/images/vscode.png" alt="VSCode Image" className="w-3/4" />
        </div>
        {children}
      </body>
    </html>
  );
}
